"""Prompt constants exported for easy imports."""

from .prompts import (
    PROMPT_REGISTRY,
    STT_CLASSIFY_SYSTEM_PROMPT,
    STT_WHISPER_PROMPT,
    TTS_GENERAL_SMOOTHER_SYSTEM_PROMPT,
    API_O_PHIA_TRUOC_CO_GI_SYSTEM_PROMPT,
    API_TIM_DEN_LAY_SYSTEM_PROMPT,
    API_O_PHIA_TRUOC_CO_GI_USER_TEMPLATE,
    API_TIM_DEN_LAY_USER_TEMPLATE,
    RESPONSE_O_PHIA_TRUOC_CO_GI_SYSTEM_PROMPT,
    RESPONSE_TIM_DEN_LAY_SYSTEM_PROMPT,
)

__all__ = [
    "PROMPT_REGISTRY",
    "STT_CLASSIFY_SYSTEM_PROMPT",
    "STT_WHISPER_PROMPT",
    "TTS_GENERAL_SMOOTHER_SYSTEM_PROMPT",
    "API_O_PHIA_TRUOC_CO_GI_SYSTEM_PROMPT",
    "API_TIM_DEN_LAY_SYSTEM_PROMPT",
    "API_O_PHIA_TRUOC_CO_GI_USER_TEMPLATE",
    "API_TIM_DEN_LAY_USER_TEMPLATE",
    "RESPONSE_O_PHIA_TRUOC_CO_GI_SYSTEM_PROMPT",
    "RESPONSE_TIM_DEN_LAY_SYSTEM_PROMPT",
]
